/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as SupRouteImport } from './routes/sup'
import { Route as ShareRouteImport } from './routes/share'
import { Route as PickRouteImport } from './routes/pick'
import { Route as MeusBoloesRouteImport } from './routes/meus-boloes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveRouteImport } from './routes/live'
import { Route as JoinRouteImport } from './routes/join'
import { Route as FinalRouteImport } from './routes/final'
import { Route as DemonstracaoRouteImport } from './routes/demonstracao'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ApoiarRouteImport } from './routes/apoiar'
import { Route as AguardandoRouteImport } from './routes/aguardando'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampeonatoSlugRouteImport } from './routes/campeonato.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as CampeonatoSlugAdminRouteImport } from './routes/campeonato.$slug.admin'

const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SupRoute = SupRouteImport.update({
  id: '/sup',
  path: '/sup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const PickRoute = PickRouteImport.update({
  id: '/pick',
  path: '/pick',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusBoloesRoute = MeusBoloesRouteImport.update({
  id: '/meus-boloes',
  path: '/meus-boloes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const FinalRoute = FinalRouteImport.update({
  id: '/final',
  path: '/final',
  getParentRoute: () => rootRouteImport,
} as any)
const DemonstracaoRoute = DemonstracaoRouteImport.update({
  id: '/demonstracao',
  path: '/demonstracao',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApoiarRoute = ApoiarRouteImport.update({
  id: '/apoiar',
  path: '/apoiar',
  getParentRoute: () => rootRouteImport,
} as any)
const AguardandoRoute = AguardandoRouteImport.update({
  id: '/aguardando',
  path: '/aguardando',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampeonatoSlugRoute = CampeonatoSlugRouteImport.update({
  id: '/campeonato/$slug',
  path: '/campeonato/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CampeonatoSlugAdminRoute = CampeonatoSlugAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => CampeonatoSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aguardando': typeof AguardandoRoute
  '/apoiar': typeof ApoiarRoute
  '/create': typeof CreateRoute
  '/demonstracao': typeof DemonstracaoRoute
  '/final': typeof FinalRoute
  '/join': typeof JoinRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/meus-boloes': typeof MeusBoloesRoute
  '/pick': typeof PickRoute
  '/share': typeof ShareRoute
  '/sup': typeof SupRoute
  '/super-admin': typeof SuperAdminRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/campeonato/$slug': typeof CampeonatoSlugRouteWithChildren
  '/campeonato/$slug/admin': typeof CampeonatoSlugAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aguardando': typeof AguardandoRoute
  '/apoiar': typeof ApoiarRoute
  '/create': typeof CreateRoute
  '/demonstracao': typeof DemonstracaoRoute
  '/final': typeof FinalRoute
  '/join': typeof JoinRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/meus-boloes': typeof MeusBoloesRoute
  '/pick': typeof PickRoute
  '/share': typeof ShareRoute
  '/sup': typeof SupRoute
  '/super-admin': typeof SuperAdminRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/campeonato/$slug': typeof CampeonatoSlugRouteWithChildren
  '/campeonato/$slug/admin': typeof CampeonatoSlugAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aguardando': typeof AguardandoRoute
  '/apoiar': typeof ApoiarRoute
  '/create': typeof CreateRoute
  '/demonstracao': typeof DemonstracaoRoute
  '/final': typeof FinalRoute
  '/join': typeof JoinRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/meus-boloes': typeof MeusBoloesRoute
  '/pick': typeof PickRoute
  '/share': typeof ShareRoute
  '/sup': typeof SupRoute
  '/super-admin': typeof SuperAdminRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/campeonato/$slug': typeof CampeonatoSlugRouteWithChildren
  '/campeonato/$slug/admin': typeof CampeonatoSlugAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aguardando'
    | '/apoiar'
    | '/create'
    | '/demonstracao'
    | '/final'
    | '/join'
    | '/live'
    | '/login'
    | '/meus-boloes'
    | '/pick'
    | '/share'
    | '/sup'
    | '/super-admin'
    | '/auth/callback'
    | '/campeonato/$slug'
    | '/campeonato/$slug/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/aguardando'
    | '/apoiar'
    | '/create'
    | '/demonstracao'
    | '/final'
    | '/join'
    | '/live'
    | '/login'
    | '/meus-boloes'
    | '/pick'
    | '/share'
    | '/sup'
    | '/super-admin'
    | '/auth/callback'
    | '/campeonato/$slug'
    | '/campeonato/$slug/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aguardando'
    | '/apoiar'
    | '/create'
    | '/demonstracao'
    | '/final'
    | '/join'
    | '/live'
    | '/login'
    | '/meus-boloes'
    | '/pick'
    | '/share'
    | '/sup'
    | '/super-admin'
    | '/auth/callback'
    | '/campeonato/$slug'
    | '/campeonato/$slug/admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AguardandoRoute: typeof AguardandoRoute
  ApoiarRoute: typeof ApoiarRoute
  CreateRoute: typeof CreateRoute
  DemonstracaoRoute: typeof DemonstracaoRoute
  FinalRoute: typeof FinalRoute
  JoinRoute: typeof JoinRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  MeusBoloesRoute: typeof MeusBoloesRoute
  PickRoute: typeof PickRoute
  ShareRoute: typeof ShareRoute
  SupRoute: typeof SupRoute
  SuperAdminRoute: typeof SuperAdminRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CampeonatoSlugRoute: typeof CampeonatoSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sup': {
      id: '/sup'
      path: '/sup'
      fullPath: '/sup'
      preLoaderRoute: typeof SupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pick': {
      id: '/pick'
      path: '/pick'
      fullPath: '/pick'
      preLoaderRoute: typeof PickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-boloes': {
      id: '/meus-boloes'
      path: '/meus-boloes'
      fullPath: '/meus-boloes'
      preLoaderRoute: typeof MeusBoloesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/final': {
      id: '/final'
      path: '/final'
      fullPath: '/final'
      preLoaderRoute: typeof FinalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demonstracao': {
      id: '/demonstracao'
      path: '/demonstracao'
      fullPath: '/demonstracao'
      preLoaderRoute: typeof DemonstracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apoiar': {
      id: '/apoiar'
      path: '/apoiar'
      fullPath: '/apoiar'
      preLoaderRoute: typeof ApoiarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aguardando': {
      id: '/aguardando'
      path: '/aguardando'
      fullPath: '/aguardando'
      preLoaderRoute: typeof AguardandoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campeonato/$slug': {
      id: '/campeonato/$slug'
      path: '/campeonato/$slug'
      fullPath: '/campeonato/$slug'
      preLoaderRoute: typeof CampeonatoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campeonato/$slug/admin': {
      id: '/campeonato/$slug/admin'
      path: '/admin'
      fullPath: '/campeonato/$slug/admin'
      preLoaderRoute: typeof CampeonatoSlugAdminRouteImport
      parentRoute: typeof CampeonatoSlugRoute
    }
  }
}

interface CampeonatoSlugRouteChildren {
  CampeonatoSlugAdminRoute: typeof CampeonatoSlugAdminRoute
}

const CampeonatoSlugRouteChildren: CampeonatoSlugRouteChildren = {
  CampeonatoSlugAdminRoute: CampeonatoSlugAdminRoute,
}

const CampeonatoSlugRouteWithChildren = CampeonatoSlugRoute._addFileChildren(
  CampeonatoSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AguardandoRoute: AguardandoRoute,
  ApoiarRoute: ApoiarRoute,
  CreateRoute: CreateRoute,
  DemonstracaoRoute: DemonstracaoRoute,
  FinalRoute: FinalRoute,
  JoinRoute: JoinRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  MeusBoloesRoute: MeusBoloesRoute,
  PickRoute: PickRoute,
  ShareRoute: ShareRoute,
  SupRoute: SupRoute,
  SuperAdminRoute: SuperAdminRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CampeonatoSlugRoute: CampeonatoSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
