/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MinhasRouteImport } from './routes/minhas'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CriarRouteImport } from './routes/criar'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VSlugRouteImport } from './routes/v.$slug'
import { Route as CriarSucessoRouteImport } from './routes/criar.sucesso'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as VotacaoSlugTelaoRouteImport } from './routes/votacao.$slug.telao'
import { Route as VotacaoSlugResultadosRouteImport } from './routes/votacao.$slug.resultados'

const MinhasRoute = MinhasRouteImport.update({
  id: '/minhas',
  path: '/minhas',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarRoute = CriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VSlugRoute = VSlugRouteImport.update({
  id: '/v/$slug',
  path: '/v/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarSucessoRoute = CriarSucessoRouteImport.update({
  id: '/sucesso',
  path: '/sucesso',
  getParentRoute: () => CriarRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const VotacaoSlugTelaoRoute = VotacaoSlugTelaoRouteImport.update({
  id: '/votacao/$slug/telao',
  path: '/votacao/$slug/telao',
  getParentRoute: () => rootRouteImport,
} as any)
const VotacaoSlugResultadosRoute = VotacaoSlugResultadosRouteImport.update({
  id: '/votacao/$slug/resultados',
  path: '/votacao/$slug/resultados',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/criar': typeof CriarRouteWithChildren
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRoute
  '/minhas': typeof MinhasRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/criar/sucesso': typeof CriarSucessoRoute
  '/v/$slug': typeof VSlugRoute
  '/votacao/$slug/resultados': typeof VotacaoSlugResultadosRoute
  '/votacao/$slug/telao': typeof VotacaoSlugTelaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/criar': typeof CriarRouteWithChildren
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRoute
  '/minhas': typeof MinhasRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/criar/sucesso': typeof CriarSucessoRoute
  '/v/$slug': typeof VSlugRoute
  '/votacao/$slug/resultados': typeof VotacaoSlugResultadosRoute
  '/votacao/$slug/telao': typeof VotacaoSlugTelaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/criar': typeof CriarRouteWithChildren
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRoute
  '/minhas': typeof MinhasRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/criar/sucesso': typeof CriarSucessoRoute
  '/v/$slug': typeof VSlugRoute
  '/votacao/$slug/resultados': typeof VotacaoSlugResultadosRoute
  '/votacao/$slug/telao': typeof VotacaoSlugTelaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/como-funciona'
    | '/criar'
    | '/login'
    | '/minha-conta'
    | '/minhas'
    | '/auth/callback'
    | '/criar/sucesso'
    | '/v/$slug'
    | '/votacao/$slug/resultados'
    | '/votacao/$slug/telao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/como-funciona'
    | '/criar'
    | '/login'
    | '/minha-conta'
    | '/minhas'
    | '/auth/callback'
    | '/criar/sucesso'
    | '/v/$slug'
    | '/votacao/$slug/resultados'
    | '/votacao/$slug/telao'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/como-funciona'
    | '/criar'
    | '/login'
    | '/minha-conta'
    | '/minhas'
    | '/auth/callback'
    | '/criar/sucesso'
    | '/v/$slug'
    | '/votacao/$slug/resultados'
    | '/votacao/$slug/telao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  CriarRoute: typeof CriarRouteWithChildren
  LoginRoute: typeof LoginRoute
  MinhaContaRoute: typeof MinhaContaRoute
  MinhasRoute: typeof MinhasRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  VSlugRoute: typeof VSlugRoute
  VotacaoSlugResultadosRoute: typeof VotacaoSlugResultadosRoute
  VotacaoSlugTelaoRoute: typeof VotacaoSlugTelaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/minhas': {
      id: '/minhas'
      path: '/minhas'
      fullPath: '/minhas'
      preLoaderRoute: typeof MinhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar': {
      id: '/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof CriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$slug': {
      id: '/v/$slug'
      path: '/v/$slug'
      fullPath: '/v/$slug'
      preLoaderRoute: typeof VSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar/sucesso': {
      id: '/criar/sucesso'
      path: '/sucesso'
      fullPath: '/criar/sucesso'
      preLoaderRoute: typeof CriarSucessoRouteImport
      parentRoute: typeof CriarRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/votacao/$slug/telao': {
      id: '/votacao/$slug/telao'
      path: '/votacao/$slug/telao'
      fullPath: '/votacao/$slug/telao'
      preLoaderRoute: typeof VotacaoSlugTelaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/votacao/$slug/resultados': {
      id: '/votacao/$slug/resultados'
      path: '/votacao/$slug/resultados'
      fullPath: '/votacao/$slug/resultados'
      preLoaderRoute: typeof VotacaoSlugResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CriarRouteChildren {
  CriarSucessoRoute: typeof CriarSucessoRoute
}

const CriarRouteChildren: CriarRouteChildren = {
  CriarSucessoRoute: CriarSucessoRoute,
}

const CriarRouteWithChildren = CriarRoute._addFileChildren(CriarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  CriarRoute: CriarRouteWithChildren,
  LoginRoute: LoginRoute,
  MinhaContaRoute: MinhaContaRoute,
  MinhasRoute: MinhasRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  VSlugRoute: VSlugRoute,
  VotacaoSlugResultadosRoute: VotacaoSlugResultadosRoute,
  VotacaoSlugTelaoRoute: VotacaoSlugTelaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
