/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as SupRouteImport } from './routes/sup'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as MinhasRouteImport } from './routes/minhas'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CriarRouteImport } from './routes/criar'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VotacaoSlugRouteImport } from './routes/votacao.$slug'
import { Route as VSlugRouteImport } from './routes/v.$slug'
import { Route as CriarSucessoRouteImport } from './routes/criar.sucesso'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as VotacaoSlugIndexRouteImport } from './routes/votacao.$slug.index'
import { Route as VotacaoSlugTelaoRouteImport } from './routes/votacao.$slug.telao'
import { Route as VotacaoSlugResultadosRouteImport } from './routes/votacao.$slug.resultados'

const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const SupRoute = SupRouteImport.update({
  id: '/sup',
  path: '/sup',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasRoute = MinhasRouteImport.update({
  id: '/minhas',
  path: '/minhas',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarRoute = CriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VotacaoSlugRoute = VotacaoSlugRouteImport.update({
  id: '/votacao/$slug',
  path: '/votacao/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VSlugRoute = VSlugRouteImport.update({
  id: '/v/$slug',
  path: '/v/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarSucessoRoute = CriarSucessoRouteImport.update({
  id: '/sucesso',
  path: '/sucesso',
  getParentRoute: () => CriarRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const VotacaoSlugIndexRoute = VotacaoSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VotacaoSlugRoute,
} as any)
const VotacaoSlugTelaoRoute = VotacaoSlugTelaoRouteImport.update({
  id: '/telao',
  path: '/telao',
  getParentRoute: () => VotacaoSlugRoute,
} as any)
const VotacaoSlugResultadosRoute = VotacaoSlugResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => VotacaoSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/criar': typeof CriarRouteWithChildren
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRoute
  '/minhas': typeof MinhasRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sup': typeof SupRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/criar/sucesso': typeof CriarSucessoRoute
  '/v/$slug': typeof VSlugRoute
  '/votacao/$slug': typeof VotacaoSlugRouteWithChildren
  '/votacao/$slug/resultados': typeof VotacaoSlugResultadosRoute
  '/votacao/$slug/telao': typeof VotacaoSlugTelaoRoute
  '/votacao/$slug/': typeof VotacaoSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/criar': typeof CriarRouteWithChildren
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRoute
  '/minhas': typeof MinhasRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sup': typeof SupRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/criar/sucesso': typeof CriarSucessoRoute
  '/v/$slug': typeof VSlugRoute
  '/votacao/$slug/resultados': typeof VotacaoSlugResultadosRoute
  '/votacao/$slug/telao': typeof VotacaoSlugTelaoRoute
  '/votacao/$slug': typeof VotacaoSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/criar': typeof CriarRouteWithChildren
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRoute
  '/minhas': typeof MinhasRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sup': typeof SupRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/criar/sucesso': typeof CriarSucessoRoute
  '/v/$slug': typeof VSlugRoute
  '/votacao/$slug': typeof VotacaoSlugRouteWithChildren
  '/votacao/$slug/resultados': typeof VotacaoSlugResultadosRoute
  '/votacao/$slug/telao': typeof VotacaoSlugTelaoRoute
  '/votacao/$slug/': typeof VotacaoSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/como-funciona'
    | '/contato'
    | '/criar'
    | '/login'
    | '/minha-conta'
    | '/minhas'
    | '/politica-de-privacidade'
    | '/sup'
    | '/termos-de-uso'
    | '/auth/callback'
    | '/criar/sucesso'
    | '/v/$slug'
    | '/votacao/$slug'
    | '/votacao/$slug/resultados'
    | '/votacao/$slug/telao'
    | '/votacao/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/como-funciona'
    | '/contato'
    | '/criar'
    | '/login'
    | '/minha-conta'
    | '/minhas'
    | '/politica-de-privacidade'
    | '/sup'
    | '/termos-de-uso'
    | '/auth/callback'
    | '/criar/sucesso'
    | '/v/$slug'
    | '/votacao/$slug/resultados'
    | '/votacao/$slug/telao'
    | '/votacao/$slug'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/como-funciona'
    | '/contato'
    | '/criar'
    | '/login'
    | '/minha-conta'
    | '/minhas'
    | '/politica-de-privacidade'
    | '/sup'
    | '/termos-de-uso'
    | '/auth/callback'
    | '/criar/sucesso'
    | '/v/$slug'
    | '/votacao/$slug'
    | '/votacao/$slug/resultados'
    | '/votacao/$slug/telao'
    | '/votacao/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ContatoRoute: typeof ContatoRoute
  CriarRoute: typeof CriarRouteWithChildren
  LoginRoute: typeof LoginRoute
  MinhaContaRoute: typeof MinhaContaRoute
  MinhasRoute: typeof MinhasRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  SupRoute: typeof SupRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  VSlugRoute: typeof VSlugRoute
  VotacaoSlugRoute: typeof VotacaoSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sup': {
      id: '/sup'
      path: '/sup'
      fullPath: '/sup'
      preLoaderRoute: typeof SupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas': {
      id: '/minhas'
      path: '/minhas'
      fullPath: '/minhas'
      preLoaderRoute: typeof MinhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar': {
      id: '/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof CriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/votacao/$slug': {
      id: '/votacao/$slug'
      path: '/votacao/$slug'
      fullPath: '/votacao/$slug'
      preLoaderRoute: typeof VotacaoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$slug': {
      id: '/v/$slug'
      path: '/v/$slug'
      fullPath: '/v/$slug'
      preLoaderRoute: typeof VSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar/sucesso': {
      id: '/criar/sucesso'
      path: '/sucesso'
      fullPath: '/criar/sucesso'
      preLoaderRoute: typeof CriarSucessoRouteImport
      parentRoute: typeof CriarRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/votacao/$slug/': {
      id: '/votacao/$slug/'
      path: '/'
      fullPath: '/votacao/$slug/'
      preLoaderRoute: typeof VotacaoSlugIndexRouteImport
      parentRoute: typeof VotacaoSlugRoute
    }
    '/votacao/$slug/telao': {
      id: '/votacao/$slug/telao'
      path: '/telao'
      fullPath: '/votacao/$slug/telao'
      preLoaderRoute: typeof VotacaoSlugTelaoRouteImport
      parentRoute: typeof VotacaoSlugRoute
    }
    '/votacao/$slug/resultados': {
      id: '/votacao/$slug/resultados'
      path: '/resultados'
      fullPath: '/votacao/$slug/resultados'
      preLoaderRoute: typeof VotacaoSlugResultadosRouteImport
      parentRoute: typeof VotacaoSlugRoute
    }
  }
}

interface CriarRouteChildren {
  CriarSucessoRoute: typeof CriarSucessoRoute
}

const CriarRouteChildren: CriarRouteChildren = {
  CriarSucessoRoute: CriarSucessoRoute,
}

const CriarRouteWithChildren = CriarRoute._addFileChildren(CriarRouteChildren)

interface VotacaoSlugRouteChildren {
  VotacaoSlugResultadosRoute: typeof VotacaoSlugResultadosRoute
  VotacaoSlugTelaoRoute: typeof VotacaoSlugTelaoRoute
  VotacaoSlugIndexRoute: typeof VotacaoSlugIndexRoute
}

const VotacaoSlugRouteChildren: VotacaoSlugRouteChildren = {
  VotacaoSlugResultadosRoute: VotacaoSlugResultadosRoute,
  VotacaoSlugTelaoRoute: VotacaoSlugTelaoRoute,
  VotacaoSlugIndexRoute: VotacaoSlugIndexRoute,
}

const VotacaoSlugRouteWithChildren = VotacaoSlugRoute._addFileChildren(
  VotacaoSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ContatoRoute: ContatoRoute,
  CriarRoute: CriarRouteWithChildren,
  LoginRoute: LoginRoute,
  MinhaContaRoute: MinhaContaRoute,
  MinhasRoute: MinhasRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  SupRoute: SupRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  VSlugRoute: VSlugRoute,
  VotacaoSlugRoute: VotacaoSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
